name = "PottsEvolver"
uuid = "288ebb56-9d8a-405a-a2d6-6ed6f22c6052"
authors = ["Pierre Barrat-Charlaix"]
version = "1.0.0-DEV"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
BioSequenceMappings = "a84bc454-70cc-4f51-8a9d-ca76a5a82222"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TreeTools = "62f0eae3-8c0e-4032-a621-7756092209e5"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
ArgCheck = "2.3.0"
julia = "1.11"

[extras]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
